repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: ^(.+\.ipynb)
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.0
    hooks:
      -  id: isort
         args: ["--profile", "black", "--filter-files"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-typing-imports==1.10.1
          - flake8-bugbear
          - flake8-docstrings
        args: ['--max-line-length=89', --config, .flake8]
        exclude: notebooks/

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3
